# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created: Thu Apr  5 07:30:59 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(636, 497)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 350, 291, 101))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_10.setMinimumSize(QtCore.QSize(60, 20))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Hue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_11.setMinimumSize(QtCore.QSize(30, 20))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_3.addWidget(self.label_11)
        self.h_slide = QtGui.QSlider(self.verticalLayoutWidget)
        self.h_slide.setMaximum(180)
        self.h_slide.setOrientation(QtCore.Qt.Horizontal)
        self.h_slide.setObjectName(_fromUtf8("h_slide"))
        self.horizontalLayout_3.addWidget(self.h_slide)
        self.h_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.h_spinBox.setMinimumSize(QtCore.QSize(60, 0))
        self.h_spinBox.setMaximum(180)
        self.h_spinBox.setObjectName(_fromUtf8("h_spinBox"))
        self.horizontalLayout_3.addWidget(self.h_spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(60, 20))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Saturation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(30, 20))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.s_slide = QtGui.QSlider(self.verticalLayoutWidget)
        self.s_slide.setMaximum(255)
        self.s_slide.setOrientation(QtCore.Qt.Horizontal)
        self.s_slide.setObjectName(_fromUtf8("s_slide"))
        self.horizontalLayout.addWidget(self.s_slide)
        self.s_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.s_spinBox.setMinimumSize(QtCore.QSize(60, 0))
        self.s_spinBox.setMaximum(255)
        self.s_spinBox.setObjectName(_fromUtf8("s_spinBox"))
        self.horizontalLayout.addWidget(self.s_spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(60, 0))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(30, 20))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        self.v_slide = QtGui.QSlider(self.verticalLayoutWidget)
        self.v_slide.setMaximum(255)
        self.v_slide.setOrientation(QtCore.Qt.Horizontal)
        self.v_slide.setObjectName(_fromUtf8("v_slide"))
        self.horizontalLayout_2.addWidget(self.v_slide)
        self.v_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.v_spinBox.setMinimumSize(QtCore.QSize(60, 0))
        self.v_spinBox.setMaximum(255)
        self.v_spinBox.setObjectName(_fromUtf8("v_spinBox"))
        self.horizontalLayout_2.addWidget(self.v_spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(320, 350, 20, 71))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.start_camera_btn = QtGui.QPushButton(self.centralwidget)
        self.start_camera_btn.setGeometry(QtCore.QRect(340, 340, 85, 27))
        self.start_camera_btn.setText(QtGui.QApplication.translate("MainWindow", "Start Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.start_camera_btn.setObjectName(_fromUtf8("start_camera_btn"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 340, 85, 27))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Set Tracker", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(340, 380, 289, 22))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_14 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_14.setMinimumSize(QtCore.QSize(60, 0))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Tracker Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_5.addWidget(self.label_14)
        self.label_15 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_15.setMinimumSize(QtCore.QSize(30, 20))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_5.addWidget(self.label_15)
        self.t_slide = QtGui.QSlider(self.horizontalLayoutWidget_4)
        self.t_slide.setMinimum(1)
        self.t_slide.setMaximum(50)
        self.t_slide.setOrientation(QtCore.Qt.Horizontal)
        self.t_slide.setObjectName(_fromUtf8("t_slide"))
        self.horizontalLayout_5.addWidget(self.t_slide)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 330, 60, 17))
        self.label.setMinimumSize(QtCore.QSize(60, 0))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Tolerance", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 60, 281, 211))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 636, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.h_slide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_11.setNum)
        QtCore.QObject.connect(self.s_slide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_7.setNum)
        QtCore.QObject.connect(self.v_slide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_9.setNum)
        QtCore.QObject.connect(self.t_slide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_15.setNum)
        QtCore.QObject.connect(self.start_camera_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pushButton.toggle)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

