# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created: Fri Apr 13 14:10:53 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1531, 780)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ASPIRE CAM MOUSE", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("acm2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(1, 4, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 2, 5, 1, 1)
        self.labtresh1 = QtGui.QLabel(self.centralwidget)
        self.labtresh1.setMinimumSize(QtCore.QSize(304, 171))
        self.labtresh1.setMaximumSize(QtCore.QSize(304, 171))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.labtresh1.setPalette(palette)
        self.labtresh1.setAutoFillBackground(True)
        self.labtresh1.setText(_fromUtf8(""))
        self.labtresh1.setObjectName(_fromUtf8("labtresh1"))
        self.gridLayout.addWidget(self.labtresh1, 5, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 2, 1, 1)
        self.labtresh2 = QtGui.QLabel(self.centralwidget)
        self.labtresh2.setMinimumSize(QtCore.QSize(304, 171))
        self.labtresh2.setMaximumSize(QtCore.QSize(304, 171))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.labtresh2.setPalette(palette)
        self.labtresh2.setAutoFillBackground(True)
        self.labtresh2.setText(_fromUtf8(""))
        self.labtresh2.setObjectName(_fromUtf8("labtresh2"))
        self.gridLayout.addWidget(self.labtresh2, 5, 5, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(1, 17, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 5, 6, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.labimage = QtGui.QLabel(self.centralwidget)
        self.labimage.setMinimumSize(QtCore.QSize(608, 352))
        self.labimage.setMaximumSize(QtCore.QSize(608, 352))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.labimage.setPalette(palette)
        self.labimage.setAutoFillBackground(True)
        self.labimage.setText(_fromUtf8(""))
        self.labimage.setObjectName(_fromUtf8("labimage"))
        self.gridLayout_5.addWidget(self.labimage, 1, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(0, 23, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(0, 23, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 11, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem7, 2, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 31, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout_5.addItem(spacerItem8, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 1, 1, 1, 5)
        spacerItem9 = QtGui.QSpacerItem(20, 31, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem9, 0, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 6, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 6, 5, 1, 1)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 5, 3, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 5, 4, 1, 1)
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout.addWidget(self.line_7, 3, 1, 1, 5)
        spacerItem13 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem13, 4, 1, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem14, 4, 5, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(1, 4, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 5, 0, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_6.addWidget(self.line_2)
        self.right = QtGui.QGridLayout()
        self.right.setMargin(0)
        self.right.setHorizontalSpacing(0)
        self.right.setObjectName(_fromUtf8("right"))
        self.motionsensor = QtGui.QGridLayout()
        self.motionsensor.setObjectName(_fromUtf8("motionsensor"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(60, 20))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Motion Senser</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.motionsensor.addWidget(self.label_3, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(60, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Sensitivity", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.motionsensor.addWidget(self.label, 0, 2, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.motionsensor.addItem(spacerItem16, 0, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setMinimumSize(QtCore.QSize(60, 20))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Hue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.h_lbl = QtGui.QLabel(self.centralwidget)
        self.h_lbl.setMinimumSize(QtCore.QSize(30, 20))
        self.h_lbl.setMaximumSize(QtCore.QSize(16777215, 20))
        self.h_lbl.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.h_lbl.setObjectName(_fromUtf8("h_lbl"))
        self.horizontalLayout_3.addWidget(self.h_lbl)
        self.h_slide = QtGui.QSlider(self.centralwidget)
        self.h_slide.setMinimumSize(QtCore.QSize(0, 20))
        self.h_slide.setMaximumSize(QtCore.QSize(16777215, 20))
        self.h_slide.setMaximum(180)
        self.h_slide.setOrientation(QtCore.Qt.Horizontal)
        self.h_slide.setObjectName(_fromUtf8("h_slide"))
        self.horizontalLayout_3.addWidget(self.h_slide)
        self.h_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.h_spinBox.setMinimumSize(QtCore.QSize(60, 0))
        self.h_spinBox.setMaximum(180)
        self.h_spinBox.setObjectName(_fromUtf8("h_spinBox"))
        self.horizontalLayout_3.addWidget(self.h_spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(60, 20))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Saturation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.s_lbl = QtGui.QLabel(self.centralwidget)
        self.s_lbl.setMinimumSize(QtCore.QSize(30, 20))
        self.s_lbl.setMaximumSize(QtCore.QSize(16777215, 20))
        self.s_lbl.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.s_lbl.setObjectName(_fromUtf8("s_lbl"))
        self.horizontalLayout.addWidget(self.s_lbl)
        self.s_slide = QtGui.QSlider(self.centralwidget)
        self.s_slide.setMinimumSize(QtCore.QSize(0, 20))
        self.s_slide.setMaximumSize(QtCore.QSize(16777215, 20))
        self.s_slide.setMaximum(255)
        self.s_slide.setOrientation(QtCore.Qt.Horizontal)
        self.s_slide.setObjectName(_fromUtf8("s_slide"))
        self.horizontalLayout.addWidget(self.s_slide)
        self.s_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.s_spinBox.setMinimumSize(QtCore.QSize(60, 0))
        self.s_spinBox.setMaximum(255)
        self.s_spinBox.setObjectName(_fromUtf8("s_spinBox"))
        self.horizontalLayout.addWidget(self.s_spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(60, 20))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self.v_lbl = QtGui.QLabel(self.centralwidget)
        self.v_lbl.setMinimumSize(QtCore.QSize(30, 20))
        self.v_lbl.setMaximumSize(QtCore.QSize(16777215, 20))
        self.v_lbl.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.v_lbl.setObjectName(_fromUtf8("v_lbl"))
        self.horizontalLayout_2.addWidget(self.v_lbl)
        self.v_slide = QtGui.QSlider(self.centralwidget)
        self.v_slide.setMinimumSize(QtCore.QSize(0, 20))
        self.v_slide.setMaximumSize(QtCore.QSize(16777215, 20))
        self.v_slide.setMaximum(255)
        self.v_slide.setOrientation(QtCore.Qt.Horizontal)
        self.v_slide.setObjectName(_fromUtf8("v_slide"))
        self.horizontalLayout_2.addWidget(self.v_slide)
        self.v_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.v_spinBox.setMinimumSize(QtCore.QSize(60, 0))
        self.v_spinBox.setMaximum(255)
        self.v_spinBox.setObjectName(_fromUtf8("v_spinBox"))
        self.horizontalLayout_2.addWidget(self.v_spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.motionsensor.addLayout(self.verticalLayout_2, 1, 0, 1, 3)
        self.right.addLayout(self.motionsensor, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.right.addWidget(self.line, 0, 1, 1, 1)
        self.clicksensor = QtGui.QGridLayout()
        self.clicksensor.setObjectName(_fromUtf8("clicksensor"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(60, 20))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Click Senser</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.clicksensor.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(60, 20))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Sensitivity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.clicksensor.addWidget(self.label_5, 0, 2, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_30 = QtGui.QLabel(self.centralwidget)
        self.label_30.setMinimumSize(QtCore.QSize(60, 20))
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Hue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_14.addWidget(self.label_30)
        self.label_31 = QtGui.QLabel(self.centralwidget)
        self.label_31.setMinimumSize(QtCore.QSize(30, 20))
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_14.addWidget(self.label_31)
        self.h_slide1 = QtGui.QSlider(self.centralwidget)
        self.h_slide1.setMinimumSize(QtCore.QSize(0, 20))
        self.h_slide1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.h_slide1.setMaximum(180)
        self.h_slide1.setOrientation(QtCore.Qt.Horizontal)
        self.h_slide1.setObjectName(_fromUtf8("h_slide1"))
        self.horizontalLayout_14.addWidget(self.h_slide1)
        self.h_spinBox1 = QtGui.QSpinBox(self.centralwidget)
        self.h_spinBox1.setMinimumSize(QtCore.QSize(60, 0))
        self.h_spinBox1.setMaximum(180)
        self.h_spinBox1.setObjectName(_fromUtf8("h_spinBox1"))
        self.horizontalLayout_14.addWidget(self.h_spinBox1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setMinimumSize(QtCore.QSize(60, 20))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Saturation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_15.addWidget(self.label_9)
        self.label_32 = QtGui.QLabel(self.centralwidget)
        self.label_32.setMinimumSize(QtCore.QSize(30, 20))
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_15.addWidget(self.label_32)
        self.s_slide1 = QtGui.QSlider(self.centralwidget)
        self.s_slide1.setMinimumSize(QtCore.QSize(0, 20))
        self.s_slide1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.s_slide1.setMaximum(255)
        self.s_slide1.setOrientation(QtCore.Qt.Horizontal)
        self.s_slide1.setObjectName(_fromUtf8("s_slide1"))
        self.horizontalLayout_15.addWidget(self.s_slide1)
        self.s_spinBox1 = QtGui.QSpinBox(self.centralwidget)
        self.s_spinBox1.setMinimumSize(QtCore.QSize(60, 0))
        self.s_spinBox1.setMaximum(255)
        self.s_spinBox1.setObjectName(_fromUtf8("s_spinBox1"))
        self.horizontalLayout_15.addWidget(self.s_spinBox1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_33 = QtGui.QLabel(self.centralwidget)
        self.label_33.setMinimumSize(QtCore.QSize(60, 20))
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_16.addWidget(self.label_33)
        self.label_34 = QtGui.QLabel(self.centralwidget)
        self.label_34.setMinimumSize(QtCore.QSize(30, 20))
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_16.addWidget(self.label_34)
        self.v_slide1 = QtGui.QSlider(self.centralwidget)
        self.v_slide1.setMinimumSize(QtCore.QSize(0, 20))
        self.v_slide1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.v_slide1.setMaximum(255)
        self.v_slide1.setOrientation(QtCore.Qt.Horizontal)
        self.v_slide1.setObjectName(_fromUtf8("v_slide1"))
        self.horizontalLayout_16.addWidget(self.v_slide1)
        self.v_spinBox1 = QtGui.QSpinBox(self.centralwidget)
        self.v_spinBox1.setMinimumSize(QtCore.QSize(60, 0))
        self.v_spinBox1.setMaximum(255)
        self.v_spinBox1.setObjectName(_fromUtf8("v_spinBox1"))
        self.horizontalLayout_16.addWidget(self.v_spinBox1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.clicksensor.addLayout(self.verticalLayout_6, 1, 0, 1, 3)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.clicksensor.addItem(spacerItem17, 0, 1, 1, 1)
        self.right.addLayout(self.clicksensor, 0, 2, 1, 1)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.right.addWidget(self.line_5, 1, 0, 1, 3)
        self.sensitivity = QtGui.QGridLayout()
        self.sensitivity.setObjectName(_fromUtf8("sensitivity"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_41 = QtGui.QLabel(self.centralwidget)
        self.label_41.setMinimumSize(QtCore.QSize(75, 20))
        self.label_41.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Click", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.horizontalLayout_20.addWidget(self.label_41)
        self.labelypos_2 = QtGui.QLabel(self.centralwidget)
        self.labelypos_2.setMinimumSize(QtCore.QSize(30, 20))
        self.labelypos_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelypos_2.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.labelypos_2.setObjectName(_fromUtf8("labelypos_2"))
        self.horizontalLayout_20.addWidget(self.labelypos_2)
        self.clickstvt_slide = QtGui.QSlider(self.centralwidget)
        self.clickstvt_slide.setMinimumSize(QtCore.QSize(0, 27))
        self.clickstvt_slide.setMaximumSize(QtCore.QSize(16777215, 27))
        self.clickstvt_slide.setMinimum(0)
        self.clickstvt_slide.setMaximum(200)
        self.clickstvt_slide.setOrientation(QtCore.Qt.Horizontal)
        self.clickstvt_slide.setObjectName(_fromUtf8("clickstvt_slide"))
        self.horizontalLayout_20.addWidget(self.clickstvt_slide)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem18)
        self.sensitivity.addLayout(self.horizontalLayout_20, 2, 0, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_40 = QtGui.QLabel(self.centralwidget)
        self.label_40.setMinimumSize(QtCore.QSize(75, 20))
        self.label_40.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Motion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_19.addWidget(self.label_40)
        self.labelypos = QtGui.QLabel(self.centralwidget)
        self.labelypos.setMinimumSize(QtCore.QSize(30, 20))
        self.labelypos.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelypos.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.labelypos.setObjectName(_fromUtf8("labelypos"))
        self.horizontalLayout_19.addWidget(self.labelypos)
        self.smooth_slide = QtGui.QSlider(self.centralwidget)
        self.smooth_slide.setMinimumSize(QtCore.QSize(0, 27))
        self.smooth_slide.setMaximumSize(QtCore.QSize(16777215, 27))
        self.smooth_slide.setMinimum(0)
        self.smooth_slide.setMaximum(20)
        self.smooth_slide.setOrientation(QtCore.Qt.Horizontal)
        self.smooth_slide.setObjectName(_fromUtf8("smooth_slide"))
        self.horizontalLayout_19.addWidget(self.smooth_slide)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem19)
        self.sensitivity.addLayout(self.horizontalLayout_19, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setMinimumSize(QtCore.QSize(60, 20))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Sensitivity</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.sensitivity.addWidget(self.label_12, 0, 0, 1, 1)
        self.trakersize = QtGui.QHBoxLayout()
        self.trakersize.setObjectName(_fromUtf8("trakersize"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setMinimumSize(QtCore.QSize(75, 20))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Tracker Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.trakersize.addWidget(self.label_16)
        self.labeltracksize = QtGui.QLabel(self.centralwidget)
        self.labeltracksize.setMinimumSize(QtCore.QSize(30, 20))
        self.labeltracksize.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labeltracksize.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.labeltracksize.setObjectName(_fromUtf8("labeltracksize"))
        self.trakersize.addWidget(self.labeltracksize)
        self.t_slide = QtGui.QSlider(self.centralwidget)
        self.t_slide.setMinimumSize(QtCore.QSize(0, 27))
        self.t_slide.setMaximumSize(QtCore.QSize(16777215, 27))
        self.t_slide.setMinimum(1)
        self.t_slide.setMaximum(100)
        self.t_slide.setOrientation(QtCore.Qt.Horizontal)
        self.t_slide.setObjectName(_fromUtf8("t_slide"))
        self.trakersize.addWidget(self.t_slide)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.trakersize.addItem(spacerItem20)
        self.sensitivity.addLayout(self.trakersize, 4, 0, 1, 1)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.sensitivity.addWidget(self.line_6, 3, 0, 1, 1)
        self.right.addLayout(self.sensitivity, 2, 0, 1, 3)
        self.sound = QtGui.QGridLayout()
        self.sound.setObjectName(_fromUtf8("sound"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setMinimumSize(QtCore.QSize(60, 20))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Roboto\'; font-size:11pt; font-weight:600;\">Sound Manager</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.sound.addWidget(self.label_11, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushsound = QtGui.QPushButton(self.centralwidget)
        self.pushsound.setMinimumSize(QtCore.QSize(128, 27))
        self.pushsound.setText(QtGui.QApplication.translate("MainWindow", "Enable / Disable", None, QtGui.QApplication.UnicodeUTF8))
        self.pushsound.setObjectName(_fromUtf8("pushsound"))
        self.horizontalLayout_5.addWidget(self.pushsound)
        self.clicksound_chkbox = QtGui.QCheckBox(self.centralwidget)
        self.clicksound_chkbox.setText(_fromUtf8(""))
        self.clicksound_chkbox.setChecked(True)
        self.clicksound_chkbox.setObjectName(_fromUtf8("clicksound_chkbox"))
        self.horizontalLayout_5.addWidget(self.clicksound_chkbox)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem21)
        self.sound.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.right.addLayout(self.sound, 3, 0, 1, 3)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.right.addItem(spacerItem22, 5, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem23)
        self.start_camera_btn = QtGui.QPushButton(self.centralwidget)
        self.start_camera_btn.setMinimumSize(QtCore.QSize(128, 0))
        self.start_camera_btn.setText(QtGui.QApplication.translate("MainWindow", "Start Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.start_camera_btn.setObjectName(_fromUtf8("start_camera_btn"))
        self.horizontalLayout_4.addWidget(self.start_camera_btn)
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(128, 0))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Mouse Control", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.mousectrlchkbox = QtGui.QCheckBox(self.centralwidget)
        self.mousectrlchkbox.setText(_fromUtf8(""))
        self.mousectrlchkbox.setObjectName(_fromUtf8("mousectrlchkbox"))
        self.horizontalLayout_4.addWidget(self.mousectrlchkbox)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.right.addLayout(self.gridLayout_2, 9, 0, 1, 3)
        self.log_txt = QtGui.QTextEdit(self.centralwidget)
        self.log_txt.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.log_txt.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.log_txt.setObjectName(_fromUtf8("log_txt"))
        self.right.addWidget(self.log_txt, 4, 0, 1, 3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem24)
        self.setmotiontrackerbtn = QtGui.QPushButton(self.centralwidget)
        self.setmotiontrackerbtn.setEnabled(False)
        self.setmotiontrackerbtn.setMinimumSize(QtCore.QSize(128, 0))
        self.setmotiontrackerbtn.setText(QtGui.QApplication.translate("MainWindow", "Set Motion Tracker", None, QtGui.QApplication.UnicodeUTF8))
        self.setmotiontrackerbtn.setObjectName(_fromUtf8("setmotiontrackerbtn"))
        self.horizontalLayout_7.addWidget(self.setmotiontrackerbtn)
        self.setclicktrackerbtn = QtGui.QPushButton(self.centralwidget)
        self.setclicktrackerbtn.setEnabled(False)
        self.setclicktrackerbtn.setMinimumSize(QtCore.QSize(128, 0))
        self.setclicktrackerbtn.setText(QtGui.QApplication.translate("MainWindow", "Set Click Tracker", None, QtGui.QApplication.UnicodeUTF8))
        self.setclicktrackerbtn.setObjectName(_fromUtf8("setclicktrackerbtn"))
        self.horizontalLayout_7.addWidget(self.setclicktrackerbtn)
        self.selectcolor = QtGui.QPushButton(self.centralwidget)
        self.selectcolor.setEnabled(False)
        self.selectcolor.setMinimumSize(QtCore.QSize(128, 0))
        self.selectcolor.setText(QtGui.QApplication.translate("MainWindow", "Select Color", None, QtGui.QApplication.UnicodeUTF8))
        self.selectcolor.setObjectName(_fromUtf8("selectcolor"))
        self.horizontalLayout_7.addWidget(self.selectcolor)
        self.right.addLayout(self.horizontalLayout_7, 6, 0, 1, 3)
        self.horizontalLayout_6.addLayout(self.right)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_6.addWidget(self.line_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1531, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionMinimize = QtGui.QAction(MainWindow)
        self.actionMinimize.setText(QtGui.QApplication.translate("MainWindow", "Minimize", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMinimize.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMinimize.setObjectName(_fromUtf8("actionMinimize"))
        self.actionSet_Motion_Tracker = QtGui.QAction(MainWindow)
        self.actionSet_Motion_Tracker.setText(QtGui.QApplication.translate("MainWindow", "Set Motion Tracker", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Motion_Tracker.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Motion_Tracker.setObjectName(_fromUtf8("actionSet_Motion_Tracker"))
        self.actionSet_Click_Tracker = QtGui.QAction(MainWindow)
        self.actionSet_Click_Tracker.setText(QtGui.QApplication.translate("MainWindow", "Set Click Tracker", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Click_Tracker.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Click_Tracker.setObjectName(_fromUtf8("actionSet_Click_Tracker"))
        self.actionSet_Color = QtGui.QAction(MainWindow)
        self.actionSet_Color.setText(QtGui.QApplication.translate("MainWindow", "Set Color", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Color.setShortcut(QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Color.setObjectName(_fromUtf8("actionSet_Color"))
        self.actionSet_Mouse_Control = QtGui.QAction(MainWindow)
        self.actionSet_Mouse_Control.setText(QtGui.QApplication.translate("MainWindow", "Set Mouse Control", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Mouse_Control.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+M", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Mouse_Control.setObjectName(_fromUtf8("actionSet_Mouse_Control"))
        self.menuFile.addAction(self.actionSet_Motion_Tracker)
        self.menuFile.addAction(self.actionSet_Click_Tracker)
        self.menuFile.addAction(self.actionSet_Color)
        self.menuFile.addAction(self.actionSet_Mouse_Control)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionMinimize)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.h_slide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.h_lbl.setNum)
        QtCore.QObject.connect(self.s_slide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.s_lbl.setNum)
        QtCore.QObject.connect(self.v_slide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.v_lbl.setNum)
        QtCore.QObject.connect(self.smooth_slide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.labelypos.setNum)
        QtCore.QObject.connect(self.clickstvt_slide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.labelypos_2.setNum)
        QtCore.QObject.connect(self.t_slide, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.labeltracksize.setNum)
        QtCore.QObject.connect(self.h_slide1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_31.setNum)
        QtCore.QObject.connect(self.s_slide1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_32.setNum)
        QtCore.QObject.connect(self.v_slide1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_34.setNum)
        QtCore.QObject.connect(self.pushsound, QtCore.SIGNAL(_fromUtf8("clicked()")), self.clicksound_chkbox.toggle)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), self.mousectrlchkbox.toggle)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QObject.connect(self.actionMinimize, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.showMinimized)
        QtCore.QObject.connect(MainWindow, QtCore.SIGNAL(_fromUtf8("destroyed()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

